### ISSUE TITLE
configurable port

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-serve-blobs#2]
I was wondering what else in the ssb stack depends on port 26835. I was trying to run 2 instances of ssb on one machine and the hard coded port caused an error. If there is a way we could pass in a port that seems ideal, but seems like it could be tricky with the plugin architecture.

**Comment by staltz** [comment]
Shouldn't be too tricky if it's based on the config object, which can be specified in JS separately for each app. Or this plugin can silently ignore the "port used" error since it's harmless (I think) to use one shared server for serving blobs.

**Comment by staltz** [comment]
This is now possible. See readme
