### ISSUE TITLE
Support byte ranges for audio blobs (iOS needs it)

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-serve-blobs#7]
See https://gitlab.com/staltz/manyverse/-/issues/846

iOS playback is failing due to error `Could not initialize player: Domain=AVFoundationErrorDomain Code=-11850` also known as "The server is not correctly configured", see https://developer.apple.com/documentation/avfoundation/averror/code/serverincorrectlyconfigured

> This might mean that the server does not support byte range requests.

We might have to update ssb-serve-blobs so that it supports byte range requests.

See also:

- https://www.npmjs.com/package/accept-ranges
- https://www.npmjs.com/package/byte-range-stream

**Comment by clehner** [comment]
[multiblob-http](https://github.com/ssbc/multiblob-http) (used by [ssb-ws](https://github.com/ssbc/ssb-ws)) supports range requests: https://github.com/ssbc/multiblob-http/blob/master/index.js

**Comment by staltz** [comment]
Done in 3.0

I actually ended up using multiblob-http in this module.
